# Анализ данных из Росстат

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# загрузка данных
raw_data = pd.read_excel("cen-god.xls")
raw_data.head()

Unnamed: 0  \
0                                                NaN   
1                                        ПОКАЗАТЕЛИ    
2  Средние потребительские цены на отдельные виды...   
3                  Говядина (кроме бескостного мяса)   
4                   Свинина (кроме бескостного мяса)   

                                          Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0  Средние потребительские цены по Российской Фед...        NaN        NaN   
1                                               1991       1992       1993   
2                                                NaN        NaN        NaN   
3                                              15.54      221.5    2201.27   
4                                              14.38        260    2672.81   

  Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
0        NaN        NaN        NaN        NaN        NaN        NaN  ...   
1       1994       1995       1996       1997       1998       1999  ...   
2        NaN        NaN        NaN        NaN        NaN        NaN  ...   
3    5186.28      12547      14137      15787      30.04      42.01  ...   
4    6579.38      15053      16810      19055      33.99      43.37  ...   

  Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26  \
0         NaN         NaN         NaN         NaN         NaN         NaN   
1        2011        2012     2013.00        2014        2015        2016   
2         NaN         NaN         NaN         NaN         NaN         NaN   
3      234.49      248.47      244.55      272.28      314.94      315.02   
4      210.89      220.09      214.18      272.36      271.08      264.32   

  Unnamed: 27 Unnamed: 28 Unnamed: 29 Unnamed: 30  
0         NaN         NaN         NaN         NaN  
1        2017        2018        2019        2020  
2         NaN         NaN         NaN         NaN  
3      320.34      330.58      350.05      361.04  
4      255.87      275.26      264.55      269.14  

[5 rows x 31 columns]

In [3]:
raw_data_2 = raw_data.dropna()
raw_data_2.head()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  \
1                        ПОКАЗАТЕЛИ        1991       1992       1993   
3  Говядина (кроме бескостного мяса)      15.54      221.5    2201.27   
4   Свинина (кроме бескостного мяса)      14.38        260    2672.81   
5     Куры охлажденные и мороженые1)      13.57     194.76    2238.98   
6                  Колбаса вареная2)         17        271     3351.3   

  Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
1       1994       1995       1996       1997       1998       1999  ...   
3    5186.28      12547      14137      15787      30.04      42.01  ...   
4    6579.38      15053      16810      19055      33.99      43.37  ...   
5    5677.09      11587      13815      16061      30.74      39.28  ...   
6     8984.1      20016      22859      26767      43.81      61.56  ...   

  Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26  \
1        2011        2012     2013.00        2014        2015        2016   
3      234.49      248.47      244.55      272.28      314.94      315.02   
4      210.89      220.09      214.18      272.36      271.08      264.32   
5      103.57      117.26      107.03      136.14      133.73      138.49   
6      270.28      288.23      302.94      310.54      344.81      351.27   

  Unnamed: 27 Unnamed: 28 Unnamed: 29 Unnamed: 30  
1        2017        2018        2019        2020  
3      320.34      330.58      350.05      361.04  
4      255.87      275.26      264.55      269.14  
5      126.29      151.27      143.13      145.55  
6      360.88      382.98      399.37      406.84  

[5 rows x 31 columns]

In [4]:
# строку с датами переделалив индексную строчки для столбцов
raw_data_2.columns = raw_data_2.loc[1, :]
raw_data_2.head()

1                        ПОКАЗАТЕЛИ    1991    1992     1993     1994   1995  \
1                        ПОКАЗАТЕЛИ    1991    1992     1993     1994   1995   
3  Говядина (кроме бескостного мяса)  15.54   221.5  2201.27  5186.28  12547   
4   Свинина (кроме бескостного мяса)  14.38     260  2672.81  6579.38  15053   
5     Куры охлажденные и мороженые1)  13.57  194.76  2238.98  5677.09  11587   
6                  Колбаса вареная2)     17     271   3351.3   8984.1  20016   

1   1996   1997   1998   1999  ...    2011    2012   2013.0    2014    2015  \
1   1996   1997   1998   1999  ...    2011    2012  2013.00    2014    2015   
3  14137  15787  30.04  42.01  ...  234.49  248.47   244.55  272.28  314.94   
4  16810  19055  33.99  43.37  ...  210.89  220.09   214.18  272.36  271.08   
5  13815  16061  30.74  39.28  ...  103.57  117.26   107.03  136.14  133.73   
6  22859  26767  43.81  61.56  ...  270.28  288.23   302.94  310.54  344.81   

1    2016    2017    2018    2019    2020  
1    2016    2017    2018    2019    2020  
3  315.02  320.34  330.58  350.05  361.04  
4  264.32  255.87  275.26  264.55  269.14  
5  138.49  126.29  151.27  143.13  145.55  
6  351.27  360.88  382.98  399.37  406.84  

[5 rows x 31 columns]

In [5]:
raw_data_2 = raw_data_2.drop(1)
raw_data_2.head()

1                        ПОКАЗАТЕЛИ    1991    1992     1993     1994   1995  \
3  Говядина (кроме бескостного мяса)  15.54   221.5  2201.27  5186.28  12547   
4   Свинина (кроме бескостного мяса)  14.38     260  2672.81  6579.38  15053   
5     Куры охлажденные и мороженые1)  13.57  194.76  2238.98  5677.09  11587   
6                  Колбаса вареная2)     17     271   3351.3   8984.1  20016   
7           Консервы мясные3), 350 г   8.87   163.9  1165.48  2991.46   6692   

1   1996   1997   1998   1999  ...    2011    2012  2013.0    2014    2015  \
3  14137  15787  30.04  42.01  ...  234.49  248.47  244.55  272.28  314.94   
4  16810  19055  33.99  43.37  ...  210.89  220.09  214.18  272.36  271.08   
5  13815  16061  30.74  39.28  ...  103.57  117.26  107.03  136.14  133.73   
6  22859  26767  43.81  61.56  ...  270.28  288.23  302.94  310.54  344.81   
7   7375   7811   15.5  18.16  ...   70.35   75.22   79.33   94.42  117.04   

1    2016    2017    2018    2019    2020  
3  315.02  320.34  330.58  350.05  361.04  
4  264.32  255.87  275.26  264.55  269.14  
5  138.49  126.29  151.27  143.13  145.55  
6  351.27  360.88  382.98  399.37  406.84  
7  121.37  125.21  130.13  139.47   153.5  

[5 rows x 31 columns]

In [6]:
raw_data_2.columns

Index([' ПОКАЗАТЕЛИ ',           1991,           1992,           1993,
                 1994,           1995,           1996,           1997,
                 1998,           1999,           2000,           2001,
                 2002,           2003,           2004,           2005,
                 2006,           2007,           2008,           2009,
                 2010,           2011,           2012,         2013.0,
                 2014,           2015,           2016,           2017,
                 2018,           2019,           2020],
      dtype='object', name=1)

In [7]:
col_arr = np.array(raw_data_2.columns)
col_arr

array([' ПОКАЗАТЕЛИ ', 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013.0, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=object)

In [8]:
col_arr[col_arr == 2013] = 2013
col_arr = col_arr.astype("str")
col_arr

array([' ПОКАЗАТЕЛИ ', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='<U12')

In [9]:
raw_data_2.columns = col_arr
raw_data_2.head()

ПОКАЗАТЕЛИ    1991    1992     1993     1994   1995  \
3  Говядина (кроме бескостного мяса)  15.54   221.5  2201.27  5186.28  12547   
4   Свинина (кроме бескостного мяса)  14.38     260  2672.81  6579.38  15053   
5     Куры охлажденные и мороженые1)  13.57  194.76  2238.98  5677.09  11587   
6                  Колбаса вареная2)     17     271   3351.3   8984.1  20016   
7           Консервы мясные3), 350 г   8.87   163.9  1165.48  2991.46   6692   

    1996   1997   1998   1999  ...    2011    2012    2013    2014    2015  \
3  14137  15787  30.04  42.01  ...  234.49  248.47  244.55  272.28  314.94   
4  16810  19055  33.99  43.37  ...  210.89  220.09  214.18  272.36  271.08   
5  13815  16061  30.74  39.28  ...  103.57  117.26  107.03  136.14  133.73   
6  22859  26767  43.81  61.56  ...  270.28  288.23  302.94  310.54  344.81   
7   7375   7811   15.5  18.16  ...   70.35   75.22   79.33   94.42  117.04   

     2016    2017    2018    2019    2020  
3  315.02  320.34  330.58  350.05  361.04  
4  264.32  255.87  275.26  264.55  269.14  
5  138.49  126.29  151.27  143.13  145.55  
6  351.27  360.88  382.98  399.37  406.84  
7  121.37  125.21  130.13  139.47   153.5  

[5 rows x 31 columns]

In [10]:
# транспонирование
data_1 = raw_data_2.T
data_1

3   \
 ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)   
1991                                      15.54   
1992                                      221.5   
1993                                    2201.27   
1994                                    5186.28   
1995                                      12547   
1996                                      14137   
1997                                      15787   
1998                                      30.04   
1999                                      42.01   
2000                                      52.72   
2001                                      70.33   
2002                                      72.56   
2003                                       73.9   
2004                                      93.41   
2005                                     115.77   
2006                                     131.67   
2007                                     139.49   
2008                                     174.86   
2009                                      185.6   
2010                                     197.64   
2011                                     234.49   
2012                                     248.47   
2013                                     244.55   
2014                                     272.28   
2015                                     314.94   
2016                                     315.02   
2017                                     320.34   
2018                                     330.58   
2019                                     350.05   
2020                                     361.04   

                                            4   \
 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)   
1991                                     14.38   
1992                                       260   
1993                                   2672.81   
1994                                   6579.38   
1995                                     15053   
1996                                     16810   
1997                                     19055   
1998                                     33.99   
1999                                     43.37   
2000                                     58.45   
2001                                     79.22   
2002                                     80.98   
2003                                     82.42   
2004                                    110.47   
2005                                    131.64   
2006                                       142   
2007                                    149.02   
2008                                    189.42   
2009                                    193.66   
2010                                    198.35   
2011                                    210.89   
2012                                    220.09   
2013                                    214.18   
2014                                    272.36   
2015                                    271.08   
2016                                    264.32   
2017                                    255.87   
2018                                    275.26   
2019                                    264.55   
2020                                    269.14   

                                          5                  6   \
 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)   
1991                                   13.57                 17   
1992                                  194.76                271   
1993                                 2238.98             3351.3   
1994                                 5677.09             8984.1   
1995                                   11587              20016   
1996                                   13815              22859   
1997                                   16061              26767   
1998                                   30.74              43.81   
1999                                   39.28              61.56   
2000                                    48.8              77.97   
2001   

In [11]:
data_1.columns = data_1.loc[" ПОКАЗАТЕЛИ ", :]
data_1

ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)  \
 ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)   
1991                                      15.54   
1992                                      221.5   
1993                                    2201.27   
1994                                    5186.28   
1995                                      12547   
1996                                      14137   
1997                                      15787   
1998                                      30.04   
1999                                      42.01   
2000                                      52.72   
2001                                      70.33   
2002                                      72.56   
2003                                       73.9   
2004                                      93.41   
2005                                     115.77   
2006                                     131.67   
2007                                     139.49   
2008                                     174.86   
2009                                      185.6   
2010                                     197.64   
2011                                     234.49   
2012                                     248.47   
2013                                     244.55   
2014                                     272.28   
2015                                     314.94   
2016                                     315.02   
2017                                     320.34   
2018                                     330.58   
2019                                     350.05   
2020                                     361.04   

 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)  \
 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)   
1991                                     14.38   
1992                                       260   
1993                                   2672.81   
1994                                   6579.38   
1995                                     15053   
1996                                     16810   
1997                                     19055   
1998                                     33.99   
1999                                     43.37   
2000                                     58.45   
2001                                     79.22   
2002                                     80.98   
2003                                     82.42   
2004                                    110.47   
2005                                    131.64   
2006                                       142   
2007                                    149.02   
2008                                    189.42   
2009                                    193.66   
2010                                    198.35   
2011                                    210.89   
2012                                    220.09   
2013                                    214.18   
2014                                    272.36   
2015                                    271.08   
2016                                    264.32   
2017                                    255.87   
2018                                    275.26   
2019                                    264.55   
2020                                    269.14   

 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)  \
 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)   
1991                                   13.57                 17   
1992                                  194.76                271   
1993                                 2238.98             3351.3   
1994                                 5677.09             8984.1   
1995                                   11587              20016   
1996                                   13815              22859   
1997                                   16061              26767   
1998                                   30.74              43.81   
1999                                   39.28              61.56   
2000                          

In [12]:
data_1 = data_1.drop(" ПОКАЗАТЕЛИ ")
data_1

ПОКАЗАТЕЛИ  Говядина (кроме бескостного мяса)  \
1991                                     15.54   
1992                                     221.5   
1993                                   2201.27   
1994                                   5186.28   
1995                                     12547   
1996                                     14137   
1997                                     15787   
1998                                     30.04   
1999                                     42.01   
2000                                     52.72   
2001                                     70.33   
2002                                     72.56   
2003                                      73.9   
2004                                     93.41   
2005                                    115.77   
2006                                    131.67   
2007                                    139.49   
2008                                    174.86   
2009                                     185.6   
2010                                    197.64   
2011                                    234.49   
2012                                    248.47   
2013                                    244.55   
2014                                    272.28   
2015                                    314.94   
2016                                    315.02   
2017                                    320.34   
2018                                    330.58   
2019                                    350.05   
2020                                    361.04   

 ПОКАЗАТЕЛИ  Свинина (кроме бескостного мяса) Куры охлажденные и мороженые1)  \
1991                                    14.38                          13.57   
1992                                      260                         194.76   
1993                                  2672.81                        2238.98   
1994                                  6579.38                        5677.09   
1995                                    15053                          11587   
1996                                    16810                          13815   
1997                                    19055                          16061   
1998                                    33.99                          30.74   
1999                                    43.37                          39.28   
2000                                    58.45                           48.8   
2001                                    79.22                          56.92   
2002                                    80.98                          58.38   
2003                                    82.42                          69.32   
2004                                   110.47                          69.94   
2005                                   131.64                          81.35   
2006                                      142                          78.37   
2007                                   149.02                           88.2   
2008                                   189.42                          99.94   
2009                                   193.66                         103.01   
2010                                   198.35                         105.14   
2011                                   210.89                         103.57   
2012                                   220.09                         117.26   
2013                                   214.18                         107.03   
2014                                   272.36                         136.14   
2015                                   271.08                         133.73   
2016                                   264.32                         138.49   
2017                                   255.87                         126.29   
2018                                   275.26                         151.27   
2019                                   264.55                         143.13   
2020                                   269.14     

In [13]:
data_1.to_excel("rosstat_data.xlsx")

In [14]:
data_1.values

array([[15.54, 14.38, 13.57, ..., 19.64, 10.5, 4.54],
       [221.5, 260, 194.76, ..., '360,03', 122.61, 48.02],
       [2201.27, 2672.81, 2238.98, ..., 6664, 1614, 777],
       ...,
       [330.58, 275.26, 151.27, ..., 1869.54, 724.61, 382.06],
       [350.05, 264.55, 143.13, ..., 1937.53, 780.86, 398.49],
       [361.04, 269.14, 145.55, ..., 2000.21, 810.75, 398.71]],
      dtype=object)

In [15]:
data_1.loc["1995", :].unique()

array([12547, 15053, 11587, 20016, 6692, 8325, 17488, 8050, 20075, 10460,
       2812, 22514, 5345, 4486, 25747, 3115, 4811, 4592, 6511, 1882, 2094,
       2340, 6038, 20230, 37590, 22937, 5154, 283799, 403808, 42662,
       102497, 5548, 9703, 181706, 352061, 119280, 2221, 8858, 1488,
       53019, 396560, 469798, 1808916, 99732, 738304, 45899, 142340, 1681,
       '…', 1037, 864, 11532, 68702, 211722, 31882, 3320, 29269, 18519,
       229588, 232382, 656, 681, 692, 1136, 792, 3496, 11422, 267, 3584,
       5073, 471, 951, 8077, 3886, 6185, 2638, 90428, 60847, 20704, 10471],
      dtype=object)

In [16]:
data_1.loc["2014", :].unique()

array([272.28, 272.36, 136.14, 310.54, 94.42, 110.65, 292.21, 70.12,
       357.54, 78.09, 43.81, 388.81, 58.76, 44.97, 496.4, 29.46, 58.75,
       53.03, 55.18, 26.66, 25.55, 26.47, 76.7, 547.02, 1139.95, 253.64,
       87.37, 6004.43, 6772.7, 942.07, 1722.5, 63.94, 133.39, 2818.99,
       5327.88, 3092.5, 22.47, 104.73, 48.69, 722.28, 5140.87, 7412.22,
       19047.78, 1425.95, 12458.63, 409.58, 2307.75, 30.41, 11.23, 6.59,
       3.91, 260.75, 1153.52, 1231.78, 850.88, 90.7, 384.66, 343.07,
       4868.29, 3028.53, 17.5, 17.67, 16.55, 27.65, 15.11, 76.86, 422.98,
       21.98, '-', 21.42, 17.01, 109.85, 1490.71, 63.89, 314.95, 240.57,
       536.64, 76.55, 2205.2, 1614.1, 555.94, 306.95], dtype=object)

In [17]:
# замена символа '…' на 0.0
data_2 = data_1.replace('…', 0.0)
data_2.loc["1995", :].unique()

array([12547.0, 15053.0, 11587.0, 20016.0, 6692.0, 8325.0, 17488.0,
       8050.0, 20075.0, 10460.0, 2812.0, 22514.0, 5345.0, 4486.0, 25747.0,
       3115.0, 4811.0, 4592.0, 6511.0, 1882.0, 2094.0, 2340.0, 6038.0,
       20230.0, 37590.0, 22937.0, 5154.0, 283799.0, 403808.0, 42662.0,
       102497.0, 5548.0, 9703.0, 181706.0, 352061.0, 119280.0, 2221.0,
       8858.0, 1488.0, 53019.0, 396560.0, 469798.0, 1808916.0, 99732,
       738304.0, 45899, 142340, 1681, 0.0, 1037.0, 864.0, 11532, 68702,
       211722, 31882, 3320, 29269, 18519, 229588, 232382, 656, 681, 692,
       1136, 792, 3496, 11422, 267, 3584, 5073, 471, 951, 8077, 3886,
       6185, 2638, 90428, 60847, 20704, 10471], dtype=object)

In [18]:
# замена символа '-' на 0.0
data_2 = data_2.replace('-', 0.0)
data_2.loc["2014", :].unique()

array([272.28, 272.36, 136.14, 310.54, 94.42, 110.65, 292.21, 70.12,
       357.54, 78.09, 43.81, 388.81, 58.76, 44.97, 496.4, 29.46, 58.75,
       53.03, 55.18, 26.66, 25.55, 26.47, 76.7, 547.02, 1139.95, 253.64,
       87.37, 6004.43, 6772.7, 942.07, 1722.5, 63.94, 133.39, 2818.99,
       5327.88, 3092.5, 22.47, 104.73, 48.69, 722.28, 5140.87, 7412.22,
       19047.78, 1425.95, 12458.63, 409.58, 2307.75, 30.41, 11.23, 6.59,
       3.91, 260.75, 1153.52, 1231.78, 850.88, 90.7, 384.66, 343.07,
       4868.29, 3028.53, 17.5, 17.67, 16.55, 27.65, 15.11, 76.86, 422.98,
       21.98, 0.0, 21.42, 17.01, 109.85, 1490.71, 63.89, 314.95, 240.57,
       536.64, 76.55, 2205.2, 1614.1, 555.94, 306.95], dtype=object)

In [19]:
# замена символа '...' на 0.0
data_2 = data_2.replace('...', 0.0)

In [21]:
data_2.values

array([[15.54, 14.38, 13.57, ..., 19.64, 10.5, 4.54],
       [221.5, 260.0, 194.76, ..., '360,03', 122.61, 48.02],
       [2201.27, 2672.81, 2238.98, ..., 6664, 1614, 777],
       ...,
       [330.58, 275.26, 151.27, ..., 1869.54, 724.61, 382.06],
       [350.05, 264.55, 143.13, ..., 1937.53, 780.86, 398.49],
       [361.04, 269.14, 145.55, ..., 2000.21, 810.75, 398.71]],
      dtype=object)

In [22]:
object_cols = list(data_2.select_dtypes(include="object"))
object_cols

['Постановка набоек, за пару',
 'Ремонт телевизоров цветного изображения18)  ',
 'Ремонт холодильников всех марок19)',
 'Химчистка мужского костюма20)',
 'Стирка и глажение белья прямого21), за кг',
 'Стрижка модельная в женском зале22)',
 'Стрижка модельная в мужском зале',
 'Рытье могилы23)',
 'Изготовление гроба',
 'Проезд в городском автобусе, за поездку24)',
 'Проезд в трамвае, за поездку',
 'Проезд в троллейбусе, за поездку',
 'Проезд в метро, за поездку',
 'Пересылка простого письма внутри России25), массой до 20 г ',
 'Отправка телеграммы обыкновенной внутренней26), за 15 слов',
 'Абонентская плата за неограниченный объем местных телефонных соединений, за месяц',
 'Плата за жилье в домах государственного и муниципального жилищных фондов27), за м2 общей площади',
 'Водоснабжение холодное и водоотведение, за месяц с человека',
 'Отопление28), за м2 общей площади',
 'Газ сетевой, за месяц с человека',
 'Электроэнергия в квартирах  без электроплит за минимальный объем потребления29

In [23]:
data_2["Общий анализ крови33)"]

1991       4.54
1992      48.02
1993        777
1994    3470.18
1995      10471
1996      13922
1997      19491
1998       24.4
1999      31.22
2000      37.99
2001      46.89
2002      59.21
2003      66.94
2004      77.96
2005       94.6
2006     110.21
2007     128.21
2008     148.32
2009     174.11
2010     195,11
2011      217.7
2012     242.25
2013     277.24
2014     306.95
2015     334.21
2016     354.91
2017     370.24
2018     382.06
2019     398.49
2020     398.71
Name: Общий анализ крови33), dtype: object

In [26]:
# замена запятой внутри числа на точку
data_2[object_cols] = data_2[object_cols].replace(',', '.', regex=True)
data_2["Общий анализ крови33)"].unique()

array([4.54, 48.02, 777, 3470.18, 10471, 13922, 19491, 24.4, 31.22, 37.99,
       46.89, 59.21, 66.94, 77.96, 94.6, 110.21, 128.21, 148.32, 174.11,
       '195.11', 217.7, 242.25, 277.24, 306.95, 334.21, 354.91, 370.24,
       382.06, 398.49, 398.71], dtype=object)

In [28]:
data_3 = data_2.astype('float')
data_3["Общий анализ крови33)"].unique()

array([4.54000e+00, 4.80200e+01, 7.77000e+02, 3.47018e+03, 1.04710e+04,
       1.39220e+04, 1.94910e+04, 2.44000e+01, 3.12200e+01, 3.79900e+01,
       4.68900e+01, 5.92100e+01, 6.69400e+01, 7.79600e+01, 9.46000e+01,
       1.10210e+02, 1.28210e+02, 1.48320e+02, 1.74110e+02, 1.95110e+02,
       2.17700e+02, 2.42250e+02, 2.77240e+02, 3.06950e+02, 3.34210e+02,
       3.54910e+02, 3.70240e+02, 3.82060e+02, 3.98490e+02, 3.98710e+02])