- атрибуты

In [2]:
import numpy as np

In [3]:
arr_1 = np.random.randint(10, size = (3, 5))
arr_1

array([[0, 2, 8, 4, 2],
       [0, 7, 5, 9, 3],
       [3, 0, 1, 9, 5]])

In [4]:
# мерность массива (количество измерений/осей)
arr_1.ndim

2

In [6]:
# форма массива 
arr_1.shape

(3, 5)

In [10]:
arr_1.shape[0]

3

In [13]:
# количество всех элементов массива
arr_1.size

15

In [15]:
# тип значений массива 
arr_1.dtype

dtype('int32')

In [19]:
arr_2 = np.random.random(5)
arr_2.dtype

dtype('float64')

In [23]:
arr_1.astype("int8")

array([[0, 2, 8, 4, 2],
       [0, 7, 5, 9, 3],
       [3, 0, 1, 9, 5]], dtype=int8)

- индексация

In [26]:
arr_3 = np.random.randint(10, size = (10))
arr_3

array([6, 8, 8, 9, 1, 5, 4, 2, 2, 2])

In [30]:
arr_3[1]

8

In [33]:
arr_3[-5]

5

In [35]:
# индексация 2-мерных массивов
arr_4 = np.random.randint(10, size = (2, 3))
arr_4

array([[7, 8, 2],
       [3, 4, 1]])

In [37]:
# списковый синтаксис
arr_4[1][2]

1

In [ ]:
# синтаксис numpy
arr_4[1, 2]

- срезы

In [45]:
arr_3[:5]

array([6, 8, 8, 9, 1])

In [47]:
arr_3[1:]

array([8, 8, 9, 1, 5, 4, 2, 2, 2])

In [49]:
arr_3[::-2]

array([2, 2, 5, 9, 8])

In [52]:
arr_4[0, 1:]

array([8, 2])

In [54]:
arr_4[:, :2]

array([[7, 8],
       [3, 4]])

* представления (views) и копии (copies)

In [65]:
# срез списка создает копию
# копия независима от исходного списка 
my_list = [1, 2, 3, 4, 5]
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [61]:
sub_list[0] = 100

In [63]:
sub_list

[100, 4, 5]

In [64]:
my_list

[1, 2, 3, 4, 5]

In [69]:
# срез массива является представлением исходного массива 
my_array = np.array([1,2,3,4,5])
sub_array = my_array[2:]
sub_array

array([3, 4, 5])

In [72]:
sub_array[0] = 100
sub_array

array([100,   4,   5])

In [74]:
copy_array = my_array[2:].copy()
copy_array

array([100,   4,   5])

In [75]:
copy_array[0] = 10
copy_array

array([10,  4,  5])

In [78]:
my_array

array([  1,   2, 100,   4,   5])

- изменение формы

In [81]:
# 1-мерный массив (вектор строка)
arr_5 = np.arange(1, 10)
arr_5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr_5.shape

(9,)

In [87]:
# вектор-столбец
# технически получется 2-мерный массив
arr_5.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Операции
- Универсальные функции

In [92]:
a = np.arange(5)
b = np.arange(2, 7)

print(a)
print(b)

[0 1 2 3 4]
[2 3 4 5 6]


In [95]:
# поэлементное сложение массивов
# "+" - алиас универсальной функции np.add()
a + b

array([ 2,  4,  6,  8, 10])

In [94]:
np.add(a, b)

array([ 2,  4,  6,  8, 10])

In [97]:
np.add(10, 20)

30

In [103]:
x = np.arange(4)
x

array([0, 1, 2])

In [104]:
# обычное (поэлементное) умножение (результат - произведением Адамара)
x * x

array([0, 1, 4])

In [109]:
# матричное умножение
x1 = x.reshape((3,1))
x1

array([[0],
       [1],
       [2]])

In [107]:
np.dot(x, x1)

array([5])

In [110]:
# x[0] * x1[0] + x[1] * x1[1] + x[2] * x1[2]

In [112]:
y = np.arange(6).reshape((2, 3))
y

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:
# транспонирование
y1 = y.T
y1

array([[0, 3],
       [1, 4],
       [2, 5]])

In [116]:
np.dot(y, y1)

array([[ 5, 14],
       [14, 50]])

In [117]:
# Линейная алгебра - самостоятельно