In [2]:
import numpy as np

- агрегирование

Агрегирование - вычисление неких сводных показателей.

In [4]:
arr_1 = np.random.random(10)
arr_1

array([0.48465093, 0.67115821, 0.26898316, 0.00720063, 0.78090043,
       0.31243063, 0.20534221, 0.92825282, 0.9254131 , 0.63277595])

In [7]:
# сумма
# 1D-array
np.sum(arr_1)

5.21710805754387

In [8]:
# 2D-array
np.sum(arr_1.reshape((2,5)))

5.21710805754387

In [10]:
# минимум
np.min(arr_1)

0.007200633726886507

In [11]:
np.max(arr_1)

0.9282528196890574

In [12]:
np.mean(arr_1)

0.521710805754387

- сравнения

In [15]:
arr_2 = np.arange(5)
arr_2

array([0, 1, 2, 3, 4])

In [16]:
arr_2 != 2

array([ True,  True, False,  True,  True])

In [17]:
arr_2 == 2

array([False, False,  True, False, False])

In [18]:
np.arange(10).reshape((5,2)) >= 2

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [21]:
# общее сравнение
# имеются ли в массиве какие-либо значения, отвечающие условию
np.any(arr_2 > 3)

True

In [22]:
# все ли значения отвечают условию
np.all(arr_2 < 2)

False

In [23]:
arr_3 = np.arange(10).reshape((5,2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
c = arr_3 > 5
c

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [26]:
np.any(c, axis = 0)

array([ True,  True])

In [27]:
np.any(c, axis = 1)

array([False, False, False,  True,  True])

- маскирование

In [35]:
arr_4 = np.random.randint(10, size = 5)
arr_4

array([1, 8, 2, 9, 2])

In [31]:
# массив из булевых значений - маска
c = arr_4 < 3
c

array([False,  True, False, False,  True])

In [41]:
# операция маскирования
a = arr_4[c]
a

array([8, 2])

In [43]:
arr_4[arr_4 != 2]

array([1, 8, 9])

- прихотливая индексация (fancy indieces)

In [51]:
arr_5 = np.arange(10, 20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
# с помощью списка
arr_5[[3,0,5]]

array([13, 10, 15])

In [54]:
# с помощью массива
fi = np.random.randint(len(arr_5), size = 4)
fi

array([8, 2, 5, 7])

In [55]:
arr_5[fi]

array([18, 12, 15, 17])

In [58]:
# прихотливая индексация может менять форму
fi = np.array([[3,0,1],[1,1,5]])
fi

array([[3, 0, 1],
       [1, 1, 5]])

In [59]:
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])